ALTER TABLE events
ADD COLUMN IF NOT EXISTS logo_zoom INTEGER NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS logo_offset_x INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS logo_offset_y INTEGER NOT NULL DEFAULT 0;